=== migueltomasamat/RepoLEMA/XML/xmlSchema/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellidos" type="xs:string"/>
                            <xs:element name="dni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:whiteSpace value="collapse" />
                                        <xs:pattern value="[0-9]{8}[A-Z]" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad" type="xs:string"/>
                            <xs:element name="direccion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="calle" type="xs:string"/>
                                        <xs:element name="numero" type="xs:unsignedInt"/>
                                        <xs:element name="bloque" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="piso" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="puerta" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="telefono" type="xs:string" maxOccurs="3"/>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== migueltomasamat/RepoLEMA/XML/xmlSchema/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
<cliente codigo="A-001">
    <nombre>Carlos</nombre>
    <apellidos>Garc√≠a Moreno</apellidos>
    <dni>48576876N</dni>
    <edad>28</edad>
    <direccion>
        <calle>Av. Reina Sofia</calle>
        <numero>20</numero>
    </direccion>
    <telefono>965371111</telefono>
    <telefono>658976547</telefono>
</cliente>
</clientes>
