<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE clientes[
        <!ELEMENT clientes (cliente+)>
        <!ELEMENT cliente (nombre,apellidos,dni,edad,direccion,telefono+)>
            <!ATTLIST cliente codigo ID #REQUIRED>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT apellidos (#PCDATA)>
            <!ELEMENT dni (#PCDATA)>
            <!ELEMENT edad (#PCDATA)>
            <!ELEMENT direccion (calle,numero,bloque?,piso?,puerta?)>
                <!ELEMENT calle (#PCDATA)>
                <!ELEMENT numero (#PCDATA)>
                <!ELEMENT bloque (#PCDATA)>
                <!ELEMENT piso (#PCDATA)>
                <!ELEMENT puerta (#PCDATA)>
            <!ELEMENT telefono (#PCDATA)>
        ]>
<clientes>
    <cliente codigo="A-001">
        <nombre>Carlos</nombre>
        <apellidos>Garc√≠a Moreno</apellidos>
        <dni>48576876N</dni>
        <edad>28</edad>
        <direccion>
            <calle>Av. Reina Sofia</calle>
            <numero>20</numero>
        </direccion>
        <telefono>965371111</telefono>
        <telefono>658976547</telefono>
    </cliente>
</clientes>